package miroshka.allayshop.config;

import eu.okaeri.configs.OkaeriConfig;
import eu.okaeri.configs.ConfigManager;
import eu.okaeri.configs.annotation.Comment;
import eu.okaeri.configs.annotation.Header;
import eu.okaeri.configs.yaml.snakeyaml.YamlSnakeYamlConfigurer;
import lombok.Getter;
import lombok.Setter;
import miroshka.allayshop.shop.ShopCategory;
import miroshka.allayshop.shop.ShopProduct;
import miroshka.allayshop.shop.ShopProductType;
import miroshka.allayshop.shop.offer.SpecialOfferSettings;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@Getter
@Setter
@Header("AllayShop configuration")
public class ShopConfig extends OkaeriConfig {
    @Comment("Command aliases are generated by Allay command registry only when command supports them.")
    private String title = "Магазин";

    @Comment("Aconomy/EconomyAPI currency used for shop prices.")
    private String currency = "coins";

    @Comment("Categories shown in the main shop form.")
    private List<ShopCategory> categories = defaultCategories();

    @Comment("Special offer settings.")
    private SpecialOfferSettings specialOffer = SpecialOfferSettings.defaults();

    public static ShopConfig loadConfig(Path dataFolder) {
        return ConfigManager.create(ShopConfig.class, config -> {
            config.withConfigurer(new YamlSnakeYamlConfigurer());
            config.withBindFile(dataFolder.resolve("shop.yml"));
            config.saveDefaults();
            config.load(true);
        });
    }

    private static List<ShopCategory> defaultCategories() {
        var food = new ShopCategory();
        food.setId("food");
        food.setName("Еда");
        food.setDescription("Базовые товары для выживания");
        food.setImageType("path");
        food.setImage("textures/items/carrot");

        var carrot = new ShopProduct();
        carrot.setId("carrot");
        carrot.setName("Морковь");
        carrot.setDescription("Обычная морковь для еды или торговли");
        carrot.setType(ShopProductType.ITEM);
        carrot.setMinAmount(8);
        carrot.setPrice(4000);
        carrot.setAmountScrollEnabled(true);
        carrot.setItem(new ShopProduct.ItemReward("minecraft:carrot", 0, null, List.of(), Map.of()));

        var fixed = new ShopProduct();
        fixed.setId("speed");
        fixed.setName("Скорость I");
        fixed.setDescription("Эффект на 60 секунд");
        fixed.setType(ShopProductType.EFFECT);
        fixed.setMinAmount(1);
        fixed.setPrice(2500);
        fixed.setAmountScrollEnabled(false);
        fixed.setEffect(new ShopProduct.EffectReward("minecraft:speed", 1, 60, false));

        food.setProducts(new ArrayList<>(List.of(carrot, fixed)));
        return new ArrayList<>(List.of(food));
    }
}
